lista = [10,20,30,40,50,60,70,80,81,82,83,84,85]
print (lista)
lista.sort() ##vai deixar a lista organizada de ordem crescente
print (lista)
lista.pop()##Exclui o ultimo item da lista
lista.pop ()## Se for em seguida, ele vai excluir o penultimo e o ultimo
print (lista)
lista.insert(3,19)## 1° umero da lista será a posição, 2° será o número do item ou cadeia pra substituir na posição determinada.
print(lista)
len(lista)
